all:
#	make -C LibCore
#	make -C PeerSDK/LibPeer
#	make -C PeerSDK/LibX10
#	make -C PeerSDK/LibX11
#	make -C PeerSDK/LibX11Z
#	make -C PeerSDK/LibMoai
#	make -C PeerSDK/LibMaya
#	make -C WebService/LibWeb
	make -C PeerSDK/PeerSDK   static=true
#	make -C LibPeerMedia
#	make -C iWatchDVR2/jni